const pains = [
  {
    emoji: "😤",
    before: "Double-booking nightmares",
    after: "Conflict-free smart scheduling",
    description:
      "Your calendar knows your capacity. GroomGrid blocks conflicts, respects buffer time, and handles last-minute reschedules automatically.",
  },
  {
    emoji: "👻",
    before: "No-shows kill your income",
    after: "Automated reminders cut no-shows 90%",
    description:
      "Smart SMS + email reminders go out 48 hours and 2 hours before appointments. Clients confirm with one tap. You get paid either way.",
  },
  {
    emoji: "📋",
    before: "Paper notes you can't find",
    after: "Grooming notes generated by AI",
    description:
      "Snap a photo after each groom. AI logs coat condition, style notes, and next-visit recommendations. Every dog's history, searchable instantly.",
  },
  {
    emoji: "📞",
    before: "Chasing clients to rebook",
    after: "Clients rebook themselves",
    description:
      "GroomGrid analyzes each dog's breed and grooming history, then sends personalized rebooking suggestions at exactly the right time.",
  },
];

export default function PainPoints() {
  return (
    <section className="py-24 bg-white" id="pain-points">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section header */}
        <div className="text-center mb-16">
          <div className="inline-block px-4 py-1.5 rounded-full bg-coral-50 border border-coral-200 text-coral-600 text-sm font-medium mb-4">
            The Old Way vs. GroomGrid
          </div>
          <h2 className="font-display text-4xl md:text-5xl font-extrabold text-gray-900 mb-4">
            You love dogs.{" "}
            <span className="text-gradient">You didn&apos;t sign up for spreadsheets.</span>
          </h2>
          <p className="text-xl text-gray-500 max-w-2xl mx-auto">
            Running a grooming business is exhausting when the tools fight you.
            GroomGrid fixes the friction, one appointment at a time.
          </p>
        </div>

        {/* Pain → Gain grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {pains.map((item) => (
            <div
              key={item.before}
              className="group relative bg-gradient-to-br from-gray-50 to-white rounded-2xl border border-gray-200 p-6 card-hover overflow-hidden"
            >
              {/* Background accent */}
              <div className="absolute inset-0 bg-gradient-to-br from-teal-50/0 to-teal-50/60 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />

              <div className="relative">
                <div className="text-3xl mb-4">{item.emoji}</div>

                {/* Before/after */}
                <div className="flex flex-col gap-2 mb-4">
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-red-500 uppercase tracking-wide">
                      Before
                    </span>
                    <div className="flex-1 h-px bg-red-100" />
                  </div>
                  <p className="text-gray-500 line-through text-sm">{item.before}</p>

                  <div className="flex items-center gap-2 mt-2">
                    <span className="text-xs font-bold text-teal-600 uppercase tracking-wide">
                      GroomGrid
                    </span>
                    <div className="flex-1 h-px bg-teal-100" />
                  </div>
                  <p className="font-display font-bold text-lg text-gray-900">
                    {item.after}
                  </p>
                </div>

                <p className="text-sm text-gray-600 leading-relaxed">{item.description}</p>
              </div>
            </div>
          ))}
        </div>

        {/* Testimonial */}
        <div className="mt-16 bg-gradient-to-br from-teal-600 to-teal-700 rounded-3xl p-8 md:p-12 text-white text-center">
          <div className="text-4xl mb-4">🐾</div>
          <blockquote className="font-display text-2xl md:text-3xl font-bold mb-6 max-w-3xl mx-auto leading-snug">
            &ldquo;I spent 2 hours every Sunday just organizing my schedule.
            Now my business runs while I&apos;m elbow-deep in a Golden Retriever.&rdquo;
          </blockquote>
          <div className="flex items-center justify-center gap-3">
            <div className="w-10 h-10 rounded-full bg-white/20 flex items-center justify-center text-xl">
              🧑‍💼
            </div>
            <div className="text-left">
              <div className="font-semibold">Casey T.</div>
              <div className="text-teal-200 text-sm">Mobile groomer, 6 dogs/day</div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
